TE5-T447 Jetpack Navigation Component Added
jay-a-shah/kotlin_Demo-App pull request #14
Opened 2022-03-10 04:26 UTC by jay-a-shah

2022-03-11 13:35 UTC, purvesh-d requested changes

2022-03-11 13:35 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Fragments/GalleryFragment.kt
> +        inflater: LayoutInflater, container: ViewGroup?,
code formatting

2022-03-14 04:25 UTC, Purvesh-Dodiya requested changes

2022-03-14 04:25 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/demoappkotlin/MainActivity.kt
> +            val normalToast = Toast.makeText(
Why you made this multiple lines and removed single line?

2022-03-14 04:25 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Fragments/GalleryFragment.kt
> +        view.findViewById<Button>(R.id.btnNextFrag).setOnClickListener(Navigation.createNavigateOnClickListener(R.id.action_galleryFragment_to_addMessageFragment))
You can put this onClick inside `onViewCreated {}`

2022-03-14 04:25 UTC, Purvesh-Dodiya commented on app/src/main/res/layout/fragment_add_message_with_safe_args.xml
> +        android:id="@+id/textview_Recent_Fragment"
undescore??

2022-03-14 04:25 UTC, Purvesh-Dodiya commented on app/src/main/res/navigation/nav_graph.xml
> +        <action
apply code formatting

2022-03-15 04:07 UTC, purvesh-d requested changes

2022-03-15 04:07 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Fragments/GalleryFragment.kt
> +import android.view.View
unused import are there

2022-03-16 04:28 UTC, purvesh-d requested changes

2022-03-16 04:28 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/MainActivity.kt
> +
extra empty lines

2022-03-16 04:28 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/activityAndFragments/ImplicitIntent.kt
> +        }
code formatting

2022-03-16 04:39 UTC, purvesh-d approved these changes

2022-03-16 04:39 UTC, merged