TE5-T605 Web Services Implemented Without 3rd party Library
jay-a-shah/kotlin_Demo-App pull request #16
Opened 2022-03-30 07:07 UTC by jay-a-shah

2022-04-04 03:41 UTC, Purvesh-Dodiya requested changes

2022-04-04 03:41 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/demoappkotlin/WebServices/ApiInterface.kt
> +
extra empty line

2022-04-04 03:41 UTC, Purvesh-Dodiya commented on app/src/main/java/com/example/demoappkotlin/WebServices/ApiInterface.kt
> +
extra empty line

2022-04-05 06:53 UTC, purvesh-d reviewed
Check for static key in whole file

2022-04-05 06:53 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/WebServices/ApiInterface.kt
> +    @GET("/api/users/{id}")
move end point to constant

2022-04-05 06:53 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/WebServices/LoginScreenWithApi.kt
> +        credential.put("email", username)
move static key

2022-04-05 06:53 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/WebServices/LoginScreenWithApi.kt
> +            if (responseCode == 200) {
move static key

2022-04-05 08:52 UTC, purvesh-d approved these changes

2022-04-05 08:52 UTC, merged