TE5-T238 Basics of kotlin
jay-a-shah/kotlin_Demo-App pull request #2
Opened 2022-01-11 13:59 UTC by jay-a-shah

2022-01-11 14:02 UTC, purvesh-d requested changes

2022-01-11 14:02 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/BasicsKotlin.kt
> +
Remove this extra spaces.

2022-01-11 14:02 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/MainActivity.kt
> +        var p1 = 13
Apply code formatting in All files.

2022-01-12 13:46 UTC, jay-a-shah commented on app/src/main/java/com/example/demoappkotlin/BasicsKotlin.kt
> +
Okk I will resolve it

2022-01-12 13:46 UTC, jay-a-shah commented on app/src/main/java/com/example/demoappkotlin/MainActivity.kt
> +        var p1 = 13
Okk

2022-01-19 03:30 UTC, purvesh-d requested changes
Add gitignore file and .idea and autogenerated files should not included in PR.

2022-02-01 04:55 UTC, purvesh-d requested changes

2022-02-01 04:55 UTC, purvesh-d commented on .idea/gradle.xml
> +  <component name="GradleMigrationSettings" migrationVersion="1" />
Add this file in gitignore

2022-02-01 04:55 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/MainActivity.kt
> +
Extra empty lines

2022-02-02 10:44 UTC, jay-a-shah commented on app/src/main/java/com/example/demoappkotlin/MainActivity.kt
> +
ok

2022-02-02 10:44 UTC, jay-a-shah commented on .idea/gradle.xml
> +  <component name="GradleMigrationSettings" migrationVersion="1" />
ok

2022-02-08 03:52 UTC, merged