TE5-T422 ListView and Bottom Navigation
jay-a-shah/kotlin_Demo-App pull request #8
Opened 2022-02-21 04:55 UTC by jay-a-shah

2022-02-21 07:15 UTC, purvesh-d requested changes

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/AndroidManifest.xml
> +            android:label="Expandable List View"
move to string file, in whole files

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Adapters/RecycleAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecycleViewHolder {
put empty line

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Adapters/RecycleAdapter.kt
> +        holder.setIsRecyclable(false)
use apply

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/BottomNavigationActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
put extra empty line

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/BottomNavigationActivity.kt
> +                R.id.icon_home -> bottomNav.currentItem = 0
static integer

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/CustomListViewActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
put empty line before start of fun in all the files

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Fragments/FirstFragment.kt
> +
extra empty line

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Fragments/FirstFragment.kt
> +        arguments?.let {
why this is empty block of let?

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Fragments/MyFavourites.kt
> +
why empty block?

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Fragments/Recent.kt
> +        }
same

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Fragments/Recent.kt
> +        inflater: LayoutInflater, container: ViewGroup?,
code formatting

2022-02-21 07:15 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/utils/Constant.kt
> +const val One = 1
use only capital word for naming variables

2022-02-21 10:03 UTC, jay-a-shah commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/BottomNavigationActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
Okk

2022-02-21 13:16 UTC, purvesh-d requested changes

2022-02-21 13:16 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/BasicsKotlin.kt
>          myToast.duration = Toast.LENGTH_SHORT
use apply

2022-02-21 13:16 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/MainActivity.kt
> +            normalToast.setGravity(Gravity.TOP, zero, zero)
use apply

2022-02-21 13:16 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/RecyclerViewActivity.kt
> +        recyclerview.addItemDecoration(DividerItemDecoration(baseContext,
use apply

2022-02-21 13:16 UTC, purvesh-d commented on app/src/main/res/layout/activity_bottom_navigation.xml
> +        android:id="@+id/bottom_navigation"
naming

2022-02-22 03:27 UTC, purvesh-d requested changes

2022-02-22 03:27 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/BasicsKotlin.kt
> +import com.example.demoappkotlin.utils.zero
constant file should contains only capitals word, `const val ZERO = 0`

2022-02-22 03:27 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Adapters/BottomNavigationAdapter.kt
> +            zero -> Recent()
make full capital in constant, not small

2022-02-22 03:27 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Adapters/RecycleAdapter.kt
> +            chkbxView?.isChecked = listData.check
use apply

2022-02-22 03:27 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/ListViewActivity.kt
> +        val btnCustomListView = findViewById<Button>(R.id.btnListViewThree)
code formating

2022-02-23 04:49 UTC, purvesh-d requested changes

2022-02-23 04:49 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Adapters/MyAdapter.kt
> +    private var ContactList = arrayListOf<ModelList>()
variable name must start with small case

2022-02-23 04:49 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/Adapters/RecycleAdapter.kt
> +                    holder.chkbxView?.isChecked = bool
`holder.chkbxView?.isChecked = bool` this line is necessary?  try to run without it and if required then utilize apply property.

2022-02-23 04:49 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/CustomListViewActivity.kt
> +        var new = myAdapter.getItemId(2)
static integer

2022-02-23 04:49 UTC, purvesh-d commented on app/src/main/java/com/example/demoappkotlin/listView_ViewPager/SimpleListViewWithArrayActivity.kt
> +        val arrayAdapter:ArrayAdapter<*>
code formatting

2022-02-23 04:49 UTC, purvesh-d commented on app/src/main/res/layout/activity_bottom_navigation.xml
> +        app:menu="@menu/bottom_navigation" />
menu layout name should start with `menu` keyword. Like `@menu/menu_bottom_navigation`

2022-02-23 04:49 UTC, purvesh-d commented on app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
remove unnecessary comment

2022-02-23 08:50 UTC, merged